# Generated by Django 2.2.2 on 2019-06-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LobReg2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
